# Generated by Django 6.0 on 2025-12-29 18:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('branch_name', models.CharField(blank=True, max_length=100)),
                ('branch_code', models.CharField(blank=True, max_length=50)),
                ('swift_code', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('GRADE_1', 'Grade 1'), ('GRADE_2', 'Grade 2'), ('GRADE_3', 'Grade 3'), ('GRADE_4', 'Grade 4'), ('GRADE_5', 'Grade 5'), ('GRADE_6', 'Grade 6')], max_length=20)),
                ('term', models.CharField(choices=[('TERM_1', 'Term 1'), ('TERM_2', 'Term 2'), ('TERM_3', 'Term 3')], max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activity_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('technology_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('late_payment_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('grade', 'term', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('student_name', models.CharField(max_length=200)),
                ('parent_email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('payment_method', models.CharField(choices=[('CARD', 'Credit/Debit Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque')], max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('bank_reference', models.CharField(blank=True, max_length=100)),
                ('receipt_number', models.CharField(blank=True, max_length=50)),
                ('receipt_sent', models.BooleanField(default=False)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enrollment.enrollmentapplication')),
                ('fee_structure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.feestructure')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
