# Generated by Django 6.0 on 2026-01-02 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('parent_name', models.CharField(max_length=200)),
                ('parent_relationship', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('grade_applying_for', models.CharField(choices=[('GRADE_1', 'Grade 1'), ('GRADE_2', 'Grade 2'), ('GRADE_3', 'Grade 3'), ('GRADE_4', 'Grade 4'), ('GRADE_5', 'Grade 5'), ('GRADE_6', 'Grade 6'), ('GRADE_7', 'Grade 7')], max_length=20)),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('previous_grade', models.CharField(blank=True, max_length=50)),
                ('special_needs', models.TextField(blank=True, help_text='Any special educational needs, allergies, or medical conditions')),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('REVIEWED', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WAITLIST', 'Waitlisted')], default='PENDING', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('review_notes', models.TextField(blank=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('birth_certificate_provided', models.BooleanField(default=False)),
                ('previous_report_provided', models.BooleanField(default=False)),
                ('immunization_provided', models.BooleanField(default=False)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrollment Application',
                'verbose_name_plural': 'Enrollment Applications',
                'ordering': ['-application_date'],
            },
        ),
    ]
