# Generated by Django 6.0 on 2025-12-29 18:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('ACCEPTED', 'Accepted'), ('WAITLISTED', 'Waitlisted'), ('REJECTED', 'Rejected'), ('ENROLLED', 'Enrolled')], default='SUBMITTED', max_length=20)),
                ('intended_grade', models.CharField(choices=[('GRADE_1', 'Grade 1'), ('GRADE_2', 'Grade 2'), ('GRADE_3', 'Grade 3'), ('GRADE_4', 'Grade 4'), ('GRADE_5', 'Grade 5'), ('GRADE_6', 'Grade 6')], max_length=20)),
                ('intended_start_term', models.CharField(max_length=50)),
                ('child_first_name', models.CharField(max_length=100)),
                ('child_last_name', models.CharField(max_length=100)),
                ('child_dob', models.DateField()),
                ('child_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('child_nationality', models.CharField(blank=True, max_length=100)),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('parent1_name', models.CharField(max_length=100)),
                ('parent1_relationship', models.CharField(max_length=50)),
                ('parent1_email', models.EmailField(max_length=254)),
                ('parent1_phone', models.CharField(max_length=20)),
                ('parent1_occupation', models.CharField(blank=True, max_length=100)),
                ('parent2_name', models.CharField(blank=True, max_length=100)),
                ('parent2_relationship', models.CharField(blank=True, max_length=50)),
                ('parent2_email', models.EmailField(blank=True, max_length=254)),
                ('parent2_phone', models.CharField(blank=True, max_length=20)),
                ('parent2_occupation', models.CharField(blank=True, max_length=100)),
                ('home_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_relationship', models.CharField(max_length=50)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('allergies', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('medical_conditions', models.TextField(blank=True)),
                ('doctor_name', models.CharField(blank=True, max_length=100)),
                ('doctor_phone', models.CharField(blank=True, max_length=20)),
                ('birth_certificate', models.FileField(blank=True, upload_to='enrollment/documents/')),
                ('previous_report', models.FileField(blank=True, upload_to='enrollment/documents/')),
                ('immunization_record', models.FileField(blank=True, upload_to='enrollment/documents/')),
                ('parent_id_copy', models.FileField(blank=True, upload_to='enrollment/documents/')),
                ('photo', models.FileField(blank=True, upload_to='enrollment/photos/')),
                ('how_did_you_hear', models.CharField(blank=True, max_length=200)),
                ('additional_notes', models.TextField(blank=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('interview_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
    ]
